# Generated by Django 3.2.13 on 2022-05-19 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_team_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='leader',
        ),
        migrations.AlterField(
            model_name='student',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.team'),
        ),
    ]
